version: "3.9"

services:
  webapp:
    restart: always
    build: ./
    volumes:
      - ./:/app
    ports: 
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations && 
      python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000"
  
  # # worker:
  #   restart: always
  #   build: .
  #   volumes: 
  #     - ./:/app
  #   depends_on:
  #     - redis
  #     - webapp
  #   command: 'celery -A proj worker -l info'